pipeline {
    agent {
      docker {
        image 'node:lts-alpine'
      }
    }
    environment {
      NAME = 'vue-template'
    }

    stages {
      stage('run install') {
        steps {
          echo '****************************** yarn... ******************************'
          sh 'node -v'
          sh 'yarn -v'
          sh 'yarn'
        }
      }
      stage('run build') {
        steps {
          echo '****************************** yarn build... ******************************'
          sh 'yarn build'
        }
      }
      stage('run delete') {
        steps {
          echo '****************************** delete last build file... ******************************'
          sh 'rm -rf $WEB_ROOT_PATH/$NAME/*'
        }
      }
      stage('run move') {
        steps {
          echo '****************************** move file... ******************************'
          sh 'mv ./dist $WEB_ROOT_PATH/$NAME'
        }
      }
    }
}
